wcpc2_k18_homepage:
    path:     /
    defaults: { _controller: WCPC2K18Bundle:Default:index }
    
competition:
    path: /competition
    defaults: { _controller: WCPC2K18Bundle:Competition:affichage }
    
rencontre:
    path: /rencontre
    defaults: { _controller: WCPC2K18Bundle:Rencontre:add }
    
affichagecompet:
    path: /competition/{id}
    defaults: { _controller: WCPC2K18Bundle:Competition:affichagecompet }
    
match:
    path: /match
    defaults: { _controller: WCPC2K18Bundle:Rencontre:match }
    
calendrier:
    path: /calendrier
    defaults: { _controller: WCPC2K18Bundle:Rencontre:affichage }
    
pronostic:
    path: /pronostic/{referenceRencontre}
    defaults: { _controller: WCPC2K18Bundle:Prediction:pronostic }
    
#listeprediction:
   # path: /test/{user}/{rencontre}
    #defaults: { _controller: WCPC2K18Bundle:Prediction:userpredictionValide }

majscore:
    path: /maj/{referenceRencontre}
    defaults: { _controller: WCPC2K18Bundle:Rencontre:majscore }
    
    
wcpc2_k18_equipe:
    resource: "@WCPC2K18Bundle/Resources/config/routing/equipe.yml"
    prefix:   /equipe

wcpc2_k18_user:
    resource: "@WCPC2K18Bundle/Resources/config/routing/user.yml"
    prefix:   /user

