wcpc2_k18_homepage:
    path:     /
    defaults: { _controller: WCPC2K18Bundle:Default:index }
    
competition:
    path: /accueil
    defaults: { _controller: WCPC2K18Bundle:Competition:affichage }