wcpc2_k18_homepage:
    path:     /
    defaults: { _controller: WCPC2K18Bundle:Default:index }
    
competition:
    path: /accueil
    defaults: { _controller: WCPC2K18Bundle:Competition:affichage }
    
rencontre:
    path: /rencontre
    defaults: { _controller: WCPC2K18Bundle:Rencontre:add }
    
affichagecompet:
    path: /competition/{id}
    defaults: { _controller: WCPC2K18Bundle:Competition:affichagecompet }
    
match:
    path: /match
    defaults: { _controller: WCPC2K18Bundle:Rencontre:match }
    
calendrier:
    path: /calendrier
    defaults: { _controller: WCPC2K18Bundle:Rencontre:affichage }
    
    
    